# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-07 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='branch',
            field=models.CharField(default='min', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='college',
            field=models.CharField(default='iit', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='wat',
            field=models.CharField(default='1234', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Year'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], null=True),
        ),
    ]
