# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20180908_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusAmb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('number', models.CharField(max_length=10)),
                ('wat', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=10)),
                ('year', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Year'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('number', models.CharField(max_length=12)),
                ('wat', models.CharField(max_length=12)),
                ('branch', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Year'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], null=True)),
                ('event', models.CharField(max_length=100)),
            ],
        ),
    ]
