# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_campusamb_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='college',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='wat',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='year',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='edfdgfd'),
            preserve_default=False,
        ),
    ]
