# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-21 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20180914_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusamb',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campusamb',
            name='college',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='campusamb',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='campusamb',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campusamb',
            name='wat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='wat',
            field=models.CharField(max_length=100),
        ),
    ]
